analysis:
  n_cores: 1                        # The number of cores a parallelized sum of Analysis classes uses by default.
hpc:
  hpc_mode: false                   # If True, use HPC mode, which disables GUI visualization, logging to screen and other settings which are not suited to running on a super computer.
  iterations_per_update: 5000       # The number of iterations between every update (visualization, results output, etc) in HPC mode.
model:
  ignore_prior_limits: false        # If ``True`` the limits applied to priors will be ignored, where limits set upper / lower limits. This stops PriorLimitException's from being raised.
  ignore_prior_limits: false
output:
  force_pickle_overwrite: false
  info_whitespace_length: 80
  log_level: INFO
  log_to_file: false
  log_file: output.log
  model_results_decimal_places: 3
  remove_files: false
  samples_to_csv: true
parallel:
  warn_environment_variables: true
profiling:
  parallel_profile: false
  should_profile: false
  repeats: 1
test:
  check_preloads: false
  exception_override: false
  parallel_profile: false
