label:
  label:
    sigma: \sigma
    centre: x
    normalization: norm
    parameter0: a
    parameter1: b
    parameter2: c
    rate: \lambda
  superscript:
    Exponential: e
    Gaussian: g
    ModelComponent0: M0
    ModelComponent1: M1
label_format:
  format:
    sigma: '{:.2f}'
    centre: '{:.2f}'
    normalization: '{:.2f}'
    parameter0: '{:.2f}'
    parameter1: '{:.2f}'
    parameter2: '{:.2f}'
    rate: '{:.2f}'
